name: PR Source Code Check

on:
  workflow_dispatch:
  push:

jobs:
  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Run prettier
        run: yarn format
